---
title: "Results summary - plots + tables"
author: "JK"
date: "2/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

experiment_name <- "Baseline (1 motif, 300 sequences)"
nSeq = 300
motif = 1
# fraction
data_path <- "../data/experiment-results/exp01-seqLen10-nSeq300-amylogram-encoding/"
#cache_path <- "data/experiment-drake-caches/exp01_seqLen10_nSeq300_amylogram_encoding/"
cache_path <- "../data/experiment-drake-caches/exp01_seqLen10_nSeq300_amylogram_encoding/"
library(QuiPTsim)
library(drake)
library(pbapply)
cache <- drake_cache(cache_path)
paths <- readd(paths, cache = cache)
```


```{r, echo=FALSE}
print(paste0("Experiment name: ", experiment_name))
```

```{r}
ranking_methods <- c(
  "symuncert",
  "QuiPT",
  "NJMIM",
  "MRMR",
  "JMIM",
  "JMI",
  "infogain",
  "gainratio",
  "DISR",
  "Chi-squared"
  )

nonranking_methods <- c(
  "symuncert_nonranking",
  "QuiPT_nonranking",
  "infogain_nonranking",
  "gainratio_nonranking",
  "FCBF_nonranking",
  "Chi-squared_nonranking"
  )

num_reps <- grep(paste0("nMotifs_", motif), paths)
method = "QuiPT"
result_files <- paste0("result__", method, "_", num_reps, ".Rds")

```

```{r}
ranking_times <- pblapply(ranking_methods, function(method) {
  result_files <- paste0(data_path, "result__", method, "_", num_reps, ".Rds")
  collect_filtering_times(result_files)
})
names(ranking_times) <- ranking_methods

nonranking_times <- pblapply(nonranking_methods, function(method) {
  result_files <- paste0(data_path, "result__", method, "_", num_reps, ".Rds")
  collect_filtering_times(result_files)
})
names(nonranking_times) <- nonranking_methods
```
```{r}

```

```{r}
library(ggplot2)
library(dplyr)

theme_set(theme_bw())
```

```{r}
total_times <- c(ranking_times, nonranking_times)
total_times$`Chi-squared_nonranking` <- NULL
total_times$symuncert_nonranking <- NULL
total_times$infogain_nonranking <- NULL
total_times$gainratio_nonranking <- NULL
total_times$QuiPT_nonranking <- NULL
names(total_times) <- c(
  "SU",
  "QuiPT",
  "NJMIM",
  "MRMR",
  "JMIM",
  "JMI",
  "IG",
  "GR",
  "DISR",
  "Chi-squared",
  "FCBF"
)
melted_times <- reshape2::melt(total_times)

g <- ggplot(melted_times, aes(L1, value))
g + geom_boxplot() + 
#  geom_dotplot(binaxis='y', 
#               stackdir='center', 
#               dotsize = .5, 
#               fill="red") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) + 
  labs(title="Box plot + Dot plot", 
       subtitle="dummy",
       caption="dummy",
       x="dummy",
       y="dummy") +
  scale_y_continuous(trans='log2')
```

```{r}
table_text = paste0("\\begin{table}
\\centering
\\begin{tabular}{|l|cc|}  
\\hline
\\multirow{2}{*}{Method}& \\multicolumn{2}{c|}{Filtering time} \\\\
\\cline{2-3} 
 & Mean & Sd \\\\
\\hline",
paste(lapply(names(total_times), function(filtername) {
  times <- total_times[[filtername]]
  paste0(filtername, " & ", round(mean(times), 2), " & ", round(sd(times), 2), " \\\\")
  }),
  collapse=" "),"\\hline
\\end{tabular}
\\end{table}")
write(file="test.txt", table_text)
```
